stackbase/urls.py
from django.urls import path
from . import views

app_name = 'stackbase'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),

    # CRUD Function
    path('questions/', views.QuestionListView.as_view(), name="question-lists"),
    path('questions/new/', views.QuestionCreateView.as_view(), name="question-create"),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name="question-detail"),
    path('questions/<int:pk>/update/', views.QuestionUpdateView.as_view(), name="question-update"),
    path('questions/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name="question-delete"),
    path('questions/<int:pk>/comment/', views.AddCommentView.as_view(), name="question-comment"),
    path('like/<int:pk>', views.like_view, name="like_post")

]

stackprj/urls.py
from django.contrib import admin
from django.urls import path, include
from stackusers import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stackbase.urls')),

    # Authentication System
    path('register/', user_view.register, name="register"),
    path('login/', auth_view.LoginView.as_view(template_name="stackusers/login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="stackusers/logout.html"), name='logout'), 

    # Profile system
    path('profile/', user_view.profile, name="profile"),
    path('profile/update/', user_view.profile_update, name="profile_update")
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ProConnect - Where ProcDees Learn, Share, &amp; Build Solutions</title>
    <!-- <link rel="shortcut icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196"> -->
    <!-- <link rel="apple-touch-icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a"> -->
    <!-- <link rel="image_src" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <!-- <link rel="stylesheet" href="assets/css/main.css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->

</head>
<body>

<header>

<div class="nav-container">
    <nav>
        <div class="nav-brand">
            <div class="hamburger-menu-container">

                <div class="hamburger-menu">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
                <div class="nav-dropdown-menu">
                    <a href="#" class="current-link">Home</a>
                    <h5>Public</h5>
                    <ul class="nav-ul">
                        <li class="nav-item">
                            <i class="fas fa-globe-europe"></i>
                            <a href="" class="nav-link">ProConnect</a>
                        </li>
                        <li class="nav-item"><a href="#" class="nav-link">Tags</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Users</a></li>
                    </ul>
                    
                </div>
            </div>

            <a href="" class="nav-icon">
                <!-- <i class="fab fa-stack-overflow"></i> -->
                <a href="{% url 'stackbase:home' %}" style="text-decoration: none; color: black;"><div class="nav-icon-text">Pro<span class="nav-bold-text">Connect</span></a>
                <!-- <div class="nav-icon-text">stack <span class="nav-bold-text">overflow</span> -->

                
                </div>
            </a>
        </div>
        <div class="nav-base-links">
            <ul>
                <li><a href="#">About</a></li>
            </ul>
        </div>
        <div class="nav-search">
            <div class="search-container">
                <i class="fas fa-search"></i>
                <form action="" method="GET">
                    <input type="text" id="" name="search-area" placeholder="Search...">
                    <button type="submit" style="margin-left: 340px; border-radius: 25px; border: none; padding: 8px;">Search</button>
                </form>
            </div>
            <div class="search-hints">
                <div class="search-arrow-up"></div>
                <div class="search-hint-body">
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>[tag] </span> search within a tag</div>
                        <div class="hint-text"><span>user:1234 </span>  search by author</div>
                        <div class="hint-text"><span>"words here"</span> exact phrase </div>
                    </div>
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>answers:0</span> unanswered questions</div>
                        <div class="hint-text"><span> score:3  </span> posts with a 3+ score</div>
                    </div>
                </div>
                <div class="search-hint-footer">
                    <a href="#" class="btn">Ask a question</a>
                    <a href="#" class="search-help">Search help</a>
                </div>
            </div>

        </div>
        <div class="nav-right-buttons">
            <div class="search-btn">
                <i class="fas fa-search"></i>
            </div>
            {% if user.is_authenticated %}
                <a href="{% url 'login' %}" class="btn btn-login">Profile</a>
                <a href="{% url 'logout' %}" class="btn btn-register">Logout</a> 
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-login">Log in</a>
                <a href="{% url 'register' %}" class="btn btn-register">Sign up</a> 
            {% endif %}
        </div>
    </nav>
</div>
<!-- <h1 style="font-size: 20px;">hello</h1> -->
    <div style="margin-top: 10px;">
        {% if messages %}
        {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        <h4 style="text-align: center;">{{ message }}</h4>
      </div>
      {% endfor %}
    {% endif %}
    </div>

        
</header>

<!-- Add block content here -->
<!-- Add enbdblock content here -->

{% block content %}

{% endblock content %}




<!-- <script src="assets/js/main.js"></script> -->
<script src="{% static 'main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<section class="hero">
    <div class="hero-content">
        <h1 class="hero-title">We <span><3 </span> people who create solutions</h1>
        <p class="hero-paragraph">
            We build solutions that empower pharma world and connect them to solutions that enable productivity, growth, and discovery.
        </p>
        <div class="hero-options">
            <a href="{% url 'stackbase:question-lists' %}" class="btn btn-developers" style="margin-left: 5px;">Latest Questions</a>

        </div>
    </div>
</section>




<section class="questions">
    <div class="container">
       <div class="questions-content">
           <div class="questions-header">
               <h3 class="question-title">Questions are everywhere, answers are on ProConnect</h3>
           </div>
           <div class="questions-body">
               <div class="questions-body-items">
                   <div class="questions-body-item" data-id="0">
                       <img src="https://cdn.sstatic.net/Img/home/ask-a-question.svg?v=f4f2050b0297" alt="" class="question-item-icon">
                       <div class="question-item-text">Ask a question</div>
                       <div class="question-arrow-right"></div>
                   </div>
                   <div class="questions-body-item"  data-id="1">
                       <img src="https://cdn.sstatic.net/Img/home/votes.svg?v=748a8f48a8e2" alt="" class="question-item-icon">
                       <div class="question-item-text">Vote on everything</div>
                       <div class="question-arrow-right"></div>
                   </div >
                   <div class="questions-body-item"  data-id="2">
                       <img src="https://cdn.sstatic.net/Img/home/answer.svg?v=4cd8048a676c" alt="" class="question-item-icon">
                       <div class="question-item-text">Answer questions</div>
                       <div class="question-arrow-right"></div>
                   </div>
               </div>
               <div class="questions-body-item-content">
                   <img src="https://cdn.sstatic.net/Img/home/illo-feats-vote.svg?v=9d2eb0efdc17" alt="" class="question-item-content-img">
                   <h4 class="question-item-content-text">
                       Accept the answer which solved your problem to let others benefit from the valuable information.
                   </h4>
                   <a href="#" class="btn btn-orange question-item-content-btn">Create an account</a>
               </div>
               <div class="questions-body-items">
                   <div class="questions-body-item"  data-id="3">
                       <img src="https://cdn.sstatic.net/Img/home/tags.svg?v=913379eb09eb" alt="" class="question-item-icon">
                       <div class="question-item-text">Tag your question</div>
                       <div class="question-arrow-left"></div>
                   </div>
                   <div class="questions-body-item"  data-id="4">
                       <img src="https://cdn.sstatic.net/Img/home/accept.svg?v=27d5be078970" alt="" class="question-item-icon">
                       <div class="question-item-text">Accept a answer</div>
                       <div class="question-arrow-left"></div>
                   </div>
                   <div class="questions-body-item"  data-id="5">
                       <img src="https://cdn.sstatic.net/Img/home/get-recognized.svg?v=3b339d9aa10c" alt="" class="question-item-icon">
                       <div class="question-item-text">Get recognized</div>
                       <div class="question-arrow-left"></div>
                   </div>
               </div>
           </div>
           
    </div>
</section>

{% endblock content %}